# Azure Container Apps configuration
# Reference: https://learn.microsoft.com/en-us/azure/container-apps/

version: 1.0

# Pre-build command
preBuild:
  - chmod +x build.sh
  - ./build.sh

# The build.sh script will create the Docker image
# Azure will push it to your container registry
